### PR TITLE
check binary compatibility

### PR DESCRIPTION
**Pull request by yanns**

### CODE REVIEW

**Comment by yanns** [comment]
I guess I'll release a 2.0.2 version before activating this.

**Comment by nickhudkins** [comment]
@yanns based on what we have queued up in master since the 2.0.1 release, (dropping scala 2.11 is included) I suspect we wanna go with a 2.1.0 release.

Happy to do this if you don't have time, unless you want to cherry-pick a 2.0.2 release that doesn't include the 2.11 support being dropped.

Let me know how I can help :)

**Comment by yanns** [comment]
I wanted to check what are the binary incompatible changes we've made, and if it's possible to fix that.
If not, we may go with a 2.1 release yes.

**Comment by yanns** [comment]
The binary changes is minimal:
From:
```
case class UnionType[Ctx](
    types: List[ObjectType[Ctx, _]],
```
to
```
case class UnionType[Ctx](
    typesFn: () => List[ObjectType[Ctx, _]],
```
https://github.com/sangria-graphql/sangria/commit/364388c5367ff27c63db9c30ffd1ed5e19941c73

I'll push a 2.1 release mentioning that.

**Comment by yanns** [comment]
Before cutting a release for sangria, let's update some dependencies:
- https://github.com/sangria-graphql/macro-visit/releases (jvm 8 bytecore)
- https://github.com/sangria-graphql/sangria-marshalling-api/releases (jvm 8 bytecode)
- https://github.com/sangria-graphql/sangria-streaming-api/releases (jvm 8 bytecode)

**Comment by yanns** [comment]
https://github.com/sangria-graphql/macro-visit/releases/tag/v0.1.3

**Comment by yanns** [comment]
https://github.com/sangria-graphql/sangria/releases/tag/v2.1.0

**Pull request merged**
