### PR TITLE
separate the AST code from the rest

### PR DESCRIPTION
**Pull request by performantdata**
Based on PR #716. Helps solve #461 and #466.

### CODE REVIEW

**Comment by performantdata** [comment]
Next thing would be to extract the `visit` stuff from `AstNode` and pimp it back in from the other packages with an implicit conversion.

**Comment by yanns** [comment]
Can you rebase your PR on `main`  now that https://github.com/sangria-graphql/sangria/pull/716 is merged and force-push the changes.? It'll help the review. Thanks a lot!

**Comment by performantdata** [comment]
Done.

**Comment by yanns** [comment]
Thanks for all your efforts. To address https://github.com/sangria-graphql/sangria/issues/461 nor https://github.com/sangria-graphql/sangria/issues/466, one would have to create a new sbt module. Do you think you could build that on top of your changes?

**Comment by performantdata** [comment]
> one would have to create a new sbt module. Do you think you could build that on top of your changes?

Yeah. This PR is in a ready-to-merge state, but I know that it needs to go farther, here or in another PR. But at this point I'm asking whether [this](https://github.com/sangria-graphql/sangria/pull/721#issuecomment-917248081) is the right direction. Because [you looked into this problem before](https://gitter.im/sangria-graphql/sangria-dev?at=6138c72c7cd57813a8b3d83b).

**Review by yanns — APPROVED** [review]
I'm ok to merge this as it is.
Feel free to try also with a separated module.

**Comment by performantdata** [comment]
I'll take that as "don't know". 😏

**Pull request merged**
