### PR TITLE
document some of the AST & parser packages

### PR DESCRIPTION
**Pull request by performantdata**
Also:
- adds type annotations to public members, to address IDE warnings
- adds `override` modifiers
- moves some types from the huge QueryAst.scala file to their own files

### CODE REVIEW

**Review by yanns — APPROVED** [review]
💯

**Comment by performantdata** [comment]
> Could you add a rule

Done. I also added some more documentation changes.

**Comment by yanns** [comment]
> > Could you add a rule
> 
> Done. I also added some more documentation changes.

Thanks. The build is still failing though. Can you have a look?

**Comment by performantdata** [comment]
Yeah, I'm still looking at it. It's because `ListMap.keys` returns an `immutable.Iterable`, while `Map.keys` doesn't.

**Comment by performantdata** [comment]
How do you plan to deal with these binary incompatibilities @yanns ? Are you going to bump the major version, or just hope that they don't affect anyone? I guess it's all the same to me for now, just another MiMa exception.

**Comment by yanns** [comment]
> How do you plan to deal with these binary incompatibilities @yanns ? Are you going to bump the major version, or just hope that they don't affect anyone? I guess it's all the same to me for now, just another MiMa exception.

If they are minimal, I don't think a major version is necessary for that.

**Review by yanns — APPROVED** [review]
💯

**Pull request merged**
