### PR TITLE
Assorted refactorings

### PR DESCRIPTION
**Pull request by nightscape**
I'm trying to understand the code a little better and applying small refactorings here and there.
I'm grouping them by theme, so that changes you don't like can be taken out.
Any comments welcome :smiley:

### CODE REVIEW

**Comment by travisbrown** [comment]
@nightscape Would you be interested in [migrating this PR to the new GitHub organisation](https://github.com/sangria-graphql/sangria/issues/463)?

**Comment by nickhudkins** [comment]
Hey @nightscape I've rebased and broken out the commits that Oleg had mentioned being worried about (with regards to performance). 

My inclination is to drop the commits with `[WARNING]` in them unless we had some sort of benchmark to know if it has impact, even though my gut says that the changes don't scream performance issues.

I'm gonna go ahead and leave this PR open for now as is, and if I haven't heard back by early next week I'll go ahead and split the `WARNING` commits into their own PR.

**Comment by nightscape** [comment]
Hi @nickhudkins, thanks for taking care!
I wouldn't expect performance issues either (rather the other way around as the Scala collections might have optimized implementations), but your proposal about splitting into two PRs sounds like a good approach.

**Comment by nickhudkins** [comment]
@nightscape split :)

**Review by yanns — APPROVED** [review]
👍

**Pull request merged**
