### PR TITLE
Use cacheKey of id supplied to SimpleFetcherCache::clearId

### PR DESCRIPTION
**Pull request by jackl**

### CODE REVIEW

**Comment by travisbrown** [comment]
@jackl This looks reasonable to me. Would you be interested in [migrating this PR to the new GitHub organisation](https://github.com/sangria-graphql/sangria/issues/463)?

**Comment by yanns** [comment]
@jackl could you please resolve the conflicts?

**Comment by jackl** [comment]
> @jackl could you please resolve the conflicts?

Have tried, but do not understand why the build has failed.  Note that this is my first time attempting to resolve conflicts on a forked repo, so I may be doing something wrong.

**Comment by yanns** [comment]
> > @jackl could you please resolve the conflicts?
> 
> Have tried, but do not understand why the build has failed. Note that this is my first time attempting to resolve conflicts on a forked repo, so I may be doing something wrong.

We have flaky tests only with the `openjdk8 Scala: 2.11.12` configuration.
Nothing to worry about. I'll merge nevertheless.

**Pull request merged**
