### PR TITLE
Allow ListType to work with any Iterable

### PR DESCRIPTION
**Pull request by stefanolande**

### CODE REVIEW

**Comment by yanns** [comment]
Thanks @stefanolande for your contribution. Do you need any help?

**Comment by stefanolande** [comment]
Thanks @yanns . Fixed an issue with the `Resolver` and added a unit test. It should be ok now.

**Comment by yanns** [comment]
This change breaks some binary compatibility. You can add an exception like shown in https://github.com/sangria-graphql/sangria/runs/7916014423?check_suite_focus=true#step:5:58

**Comment by yanns** [comment]
@stefanolande please avoid force-push once the PR is opened. Instead, add commits.

**Comment by stefanolande** [comment]
Added the filter. I'll avoid force pushes from now on 😄

**Comment by yanns** [comment]
You can use `mimaReportBinaryIssues` locally to find out all exceptions that need to be added.

**Review by yanns — APPROVED** [review]
💯

**Pull request merged**
