### PR TITLE
deprecate `DeliveryScheme`

### LINKED ISSUE #783: remove `DeliveryScheme`
I'm raising this issue now, since we're talking about moving the `parser` package into its own library, and `DeliveryScheme` is part of that package. But the presence of this class throughout the Sangria code has been an annoyance.

Apparently [Oleg got the idea from the Parboiled2 project](https://github.com/sangria-graphql/sangria/commit/b60d2bb6311bea353f108d647a4e275c7ff7f5bb). It was [one of his earliest commits](https://github.com/sangria-graphql/sangria/commits/b60d2bb6311bea353f108d647a4e275c7ff7f5bb), and I suspect that it was a premature design choice. [The original idea in Parboiled2](https://github.com/sirthias/parboiled2/blob/b504cd883d37a50e1938ab2d3be0e0d501316251/README.rst#alternative-deliveryschemes) seems to be of dubious value itself.

So my suggestion is that, in the name of simplifying the code, that we return a `Try` where needed. This can easily be turned into an `Either` or a thrown exception.

### PR DESCRIPTION
**Pull request by performantdata**
Fixes #783.

### CODE REVIEW

**Comment by performantdata** [comment]
The deprecations are overly aggressive, coming up when there isn't any explicit use of the implicits. For instance, this comes from a new-style usage:
```
[warn] /home/michael/git/sangria/modules/core/src/test/scala/sangria/execution/ExecutorSpec.scala:1019:43: method Try in object DeliveryScheme is deprecated (since Sangria 2.1.7): Removed in 3.0. A Try result will be returned by default.
[warn]       val Success(doc) = QueryParser.parse("{eager, future}")
[warn]                                           ^
```

Better safe than sorry? Anyone who has warning set to fatal will need to `@nowarn`.

**Comment by performantdata** [comment]
@yanns This too for #783.

**Comment by yanns** [comment]
it's too aggressive.
Existing code not importing `DeliveryScheme` should not have any warnings.

**Comment by performantdata** [comment]
> Existing code not importing `DeliveryScheme` should not have any warnings.

I whittled it back to that standard.

**Review by yanns — APPROVED** [review]
👍

**Pull request merged**
