### PR TITLE
Fix enum derivation

### PR DESCRIPTION
**Pull request by wordrak**
Fix enum derivation when the enum composed of case objects but they are not within another class

### CODE REVIEW

**Comment by yanns** [comment]
@wordrak thanks a lot for the PR.
To help me reviewing this, could you explain more what the actual issue is?

**Comment by wordrak** [comment]
Hi, issue is that the `deriveEnumType` macro fails when the Enum is a "case object hierarchy" and it is not contained in another object. 

e.g.:

```
  sealed trait Fruit

  case object RedApple extends Fruit
  case object SuperBanana extends Fruit
  case object MegaOrange extends Fruit
  
  object Fruit {
    implicit val enumType = deriveEnumType[Fruit]()
  }
```

If you revert the changes in the TestCase then you see the problem.

**Comment by yanns** [comment]
instead of creating the term `derive.SuperBanana` that is failing:
```
[error] /Users/yannsimon/projects/sangria-graphql/sangria/modules/derivation/src/test/scala/sangria/macros/derive/DeriveEnumTypeMacroSpec.scala:55:48: not found: value derive
[error]       val singletonEnum = deriveEnumType[Fruit]()
[error]                                                ^
```
we know create the term `SuperBanana`.

**Review by yanns — APPROVED** [review]

**Comment by yanns** [comment]
Thanks a lot!

**Pull request merged**
