### PR TITLE
Support for repeatable directives

### LINKED ISSUE #409: Support for repeatable directives
https://github.com/graphql/graphql-js/pull/1541
https://github.com/facebook/graphql/pull/472

We also need to make sure that unique directives are properly validated: https://github.com/facebook/graphql/issues/429#issuecomment-392990065

### PR DESCRIPTION
**Pull request by OlegIlyenko**
Merge as soon as https://github.com/graphql/graphql-js/pull/1541 is merged.

Closes #409

### CODE REVIEW

**Comment by spawnia** [comment]
This should be ready as https://github.com/graphql/graphql-js/pull/1965 has landed in the reference implementation.

**Comment by spawnia** [comment]
I think this is a nice feature, but have never written a single line of Scala code in my life. I hope someone else gets to it - godspeed!

**Review by yanns — APPROVED** [review]
The code is looking good for me.
I personally don't use custom directives and I cannot judge on how useful this feature is.
Anyone here who would need that?

**Comment by nikola-mladenovic** [comment]
@yanns since the https://www.apollographql.com/docs/federation/federation-spec/#federation-schema-specification contains repeatable directives, this might be the right motivation to merge this work?

**Comment by yanns** [comment]
Repeatable directives are now in the spec: http://spec.graphql.org/October2021/#sec-Type-System.Directives

**Comment by yanns** [comment]
As there are many conflicts to fix in this PR, I've opened a new one with about the same changes: https://github.com/sangria-graphql/sangria/pull/899

**Pull request closed without merging**
